name: Cross-Platform Build and Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v4

      - name: Pythonのセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: 仮想環境の作成
        run: python -m venv venv

      - name: 仮想環境のアクティブ化と依存パッケージのインストール
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: PyInstallerで実行ファイルの作成
        run: |
          source venv/bin/activate
          pyinstaller --onefile main.py --name main_ubuntu

      - name: 実行ファイルをアーティファクトとしてアップロード
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-main
          path: dist/main_ubuntu

  test-ubuntu:
    runs-on: ubuntu-latest
    needs: build-ubuntu
    steps:
      - name: 実行ファイルのダウンロード
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-main

      - name: 実行権限の追加
        run: chmod +x ./main_ubuntu

      - name: 実行ファイルのテスト
        run: |
          echo "渋谷" | ./main_ubuntu

  build-mac:
    runs-on: macos-latest
    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v4

      - name: Pythonのセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: 仮想環境の作成
        run: python -m venv venv

      - name: 仮想環境のアクティブ化と依存パッケージのインストール
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: PyInstallerで実行ファイルの作成
        run: |
          source venv/bin/activate
          pyinstaller --onefile main.py --name main_mac

      - name: 実行ファイルをアーティファクトとしてアップロード
        uses: actions/upload-artifact@v4
        with:
          name: macos-main
          path: dist/main_mac

  test-mac:
    runs-on: macos-latest
    needs: build-mac
    steps:
      - name: 実行ファイルのダウンロード
        uses: actions/download-artifact@v4
        with:
          name: macos-main

      - name: 実行権限の追加
        run: chmod +x ./main_mac

      - name: 実行ファイルのテスト
        run: |
          echo "渋谷" | ./main_mac

  create-zip:
    runs-on: ubuntu-latest
    needs: [build-ubuntu, build-mac]
    steps:
      - name: アーティファクトのダウンロード (Ubuntu)
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-main
          path: artifacts/ubuntu

      - name: アーティファクトのダウンロード (macOS)
        uses: actions/download-artifact@v4
        with:
          name: macos-main
          path: artifacts/macos

      - name: ZIPファイルの作成
        run: zip -r all-platforms.zip artifacts/

      - name: ZIPファイルをアーティファクトとしてアップロード
        uses: actions/upload-artifact@v4
        with:
          name: all-platforms
          path: all-platforms.zip

  create-release:
    runs-on: ubuntu-latest
    needs: create-zip
    steps:
      - name: リリースの作成
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0
          release_name: "Release v1.0.0"
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: リリースにアーティファクトをアップロード (Ubuntu)
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/ubuntu/main_ubuntu
          asset_name: main_ubuntu
          asset_content_type: application/octet-stream

      - name: リリースにアーティファクトをアップロード (macOS)
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/macos/main_mac
          asset_name: main_mac
          asset_content_type: application/octet-stream

      - name: ZIPファイルのアップロード
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: all-platforms.zip
          asset_name: all-platforms.zip
          asset_content_type: application/zip